name: Setup Script Test

on:
  push:
    branches: [ jazzy ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Manually run Setup test'
jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - run: ${{ github.workspace }}/Install_Propeller_Code.sh
